### PR TITLE
Synchronize all methods that use or modify tracesToNotify

### LINKED ISSUE #26: ConcurrentModificationException in notifyNewTraces
```
Fatal Exception: java.util.ConcurrentModificationException
       at java.util.LinkedList$LinkIterator.next(LinkedList.java:124)
       at java.util.LinkedList.addAll(LinkedList.java:394)
       at java.util.LinkedList.(LinkedList.java)
       at com.github.pedrovgs.lynx.model.Lynx.notifyNewTraces(Lynx.java:156)
       at com.github.pedrovgs.lynx.model.Lynx.access$000(Lynx.java:35)
       at com.github.pedrovgs.lynx.model.Lynx$1.onTraceRead(Lynx.java:79)
       at com.github.pedrovgs.lynx.model.Logcat.notifyListener(Logcat.java:95)
       at com.github.pedrovgs.lynx.model.Logcat.readLogcat(Logcat.java:85)
       at com.github.pedrovgs.lynx.model.Logcat.run(Logcat.java:70)
```

### PR DESCRIPTION
**Pull request by stkent**
Should fix #26.

### CODE REVIEW

**Comment by stkent** [comment]
```
* What went wrong:
A problem occurred configuring root project 'Lynx'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download asm-debug-all.jar (org.ow2.asm:asm-debug-all:5.0.1)
      > Could not get resource 'https://jcenter.bintray.com/org/ow2/asm/asm-debug-all/5.0.1/asm-debug-all-5.0.1.jar'.
         > java.lang.NullPointerException (no error message)
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
BUILD FAILED
Total time: 45.59 secs
The command "./gradlew checkstyle build" exited with 1.
```

🤷‍♂️

**Comment by pedrovgs** [comment]
Sorry for the late response @stkent. Thank you so much for this PR! 😃 

Even when this is not the best implementation possible due to the usage of a ``synchronized`` modified shared by instance and being used to control the concurrent usage of two different resources, I think this implementation is valid. I think we can merge this PR as soon as the build passes in Travis CI.

I've restarted the build and if it fails, it should be related to the gradle configuration. If it fails, could you update the gralde configuration so we can merge this branch after seeing the build passing in Travis?

Thank you so much for your time and effort!

**Comment by stkent** [comment]
If you'd prefer I can switch to using synchronized blocks, it's a fast change :) Let me know!

**Comment by pedrovgs** [comment]
It's ok, thanks @stkent 😃 I'm merging this PR and waiting for #31 before releasing a new version. 

Thanks for your time and contribution!

**Pull request merged**
